require: rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - 'Gemfile'
    - 'Rakefile'
    - 'test/**/*'
    - 'app/channels/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/schema.rb'
    - 'db/seeds.rb'
    - 'config.ru'
    - 'db/migrate/**/*'
    - 'db/data/**/*'
    - 'app/views/**/*'
    - 'app/jobs/**/*'
    - 'app/mailers/**/*'

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 15

Rails/Output:
  Exclude:
    - 'db/add_categories.rb'

Style/ClassVars:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

Lint/MissingSuper:
  Enabled: false
